import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright');
const root=resolve('dist');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp'};
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!path.startsWith(root+'/')&&path!==root){res.writeHead(403).end();return;}const target=path===root?root+'/index.html':path;res.setHeader('Content-Type',mime[extname(target)]||'application/octet-stream');res.end(await readFile(target));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url=`http://127.0.0.1:${server.address().port}/`;
await mkdir('test-results',{recursive:true});
let browser;
try{
 browser=await chromium.launch({headless:true});
 for(const viewport of [{width:1360,height:900},{width:390,height:844}])await test(`complete workflow, persistence, import safety and deletion at ${viewport.width}px`,async()=>{
  const context=await browser.newContext({viewport,acceptDownloads:true});let page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);await page.getByRole('button',{name:'Nova investigação',exact:true}).click();
  await page.getByLabel('O que você quer descobrir?',{exact:true}).fill('HTTPS garante honestidade?');
  await page.getByLabel('Minha explicação antes de investigar',{exact:true}).fill('Eu achava que o cadeado garantia confiança.');
  await page.getByLabel('Minha confiança nesta explicação',{exact:true}).selectOption('média');
  await page.getByRole('button',{name:'Continuar',exact:true}).click();
  await page.getByLabel('Resposta que vou investigar',{exact:true}).fill('Todo site HTTPS é legítimo. <img src=x onerror="window.pwned=true">');
  await page.getByLabel('Resposta que vou investigar',{exact:true}).evaluate(n=>{n.focus();n.setSelectionRange(0,27);n.dispatchEvent(new Event('select'));});
  await page.getByRole('button',{name:'Criar cartão do trecho selecionado',exact:true}).click();
  await page.getByLabel('Afirmação a investigar',{exact:true}).fill('Todo site HTTPS é legítimo.');
  await page.getByRole('button',{name:'Continuar',exact:true}).click();
  await page.getByRole('button',{name:'Adicionar evidência',exact:true}).click();
  await page.getByLabel('Título da fonte',{exact:true}).fill('FTC: conexão e confiança');
  await page.getByLabel('URL (opcional para fonte impressa)',{exact:true}).fill('javascript:alert(1)');
  assert.equal(await page.getByLabel('URL (opcional para fonte impressa)',{exact:true}).getAttribute('aria-invalid'),'true');
  await page.getByLabel('URL (opcional para fonte impressa)',{exact:true}).fill('https://consumer.ftc.gov/');
  await page.getByLabel('Autoria ou instituição',{exact:true}).fill('FTC');
  await page.getByLabel('Data de consulta',{exact:true}).fill('2026-10-01');
  await page.getByLabel('Trecho ou observação relevante',{exact:true}).fill('Uma conexão criptografada também pode levar a um site fraudulento.');
  await page.getByRole('button',{name:'Continuar',exact:true}).click();
  await page.getByLabel('Como esta evidência se relaciona com a afirmação?',{exact:true}).selectOption('contradiz');
  await page.getByLabel('Por que você escolheu essa relação?',{exact:true}).fill('A proteção da conexão não verifica o operador.');
  await page.getByRole('button',{name:'Continuar',exact:true}).click();
  await page.getByLabel('Minha conclusão revisada',{exact:true}).fill('HTTPS protege a conexão, mas não garante honestidade.');
  await page.getByLabel('O que mudou no meu entendimento?',{exact:true}).fill('Passei a distinguir conexão e legitimidade.');
  await page.getByRole('button',{name:'Registrar conclusão',exact:true}).click();
  assert.equal(await page.locator('#completion-errors').count(),0);
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar JSON',exact:true}).click();const download=await downloadPromise;const json=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(json.version,1);assert.ok(json.investigations[0].completedAt);
  await page.close();page=await context.newPage();await page.goto(url);await page.getByRole('button',{name:'Continuar',exact:true}).click();assert.equal(await page.getByLabel('Minha conclusão revisada',{exact:true}).inputValue(),'HTTPS protege a conexão, mas não garante honestidade.');
  await page.getByRole('button',{name:'Ver relatório',exact:true}).click();assert.equal(await page.locator('#modal-content img').count(),0);assert.equal(await page.evaluate(()=>window.pwned),undefined);
  assert.ok((await page.locator('#modal-content').textContent()).includes('<img src=x'));
  const mdPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar Markdown',exact:true}).click();const md=await mdPromise;assert.ok((await readFile(await md.path(),'utf8')).includes('&lt;img'));
  await page.getByRole('button',{name:'Fechar janela',exact:true}).click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:`test-results/conclusion-${viewport.width}.png`,fullPage:true});
  await page.getByRole('button',{name:'Minhas investigações',exact:true}).click();
  await page.getByRole('button',{name:'Renomear',exact:true}).click();await page.getByLabel('Título da investigação',{exact:true}).fill('Investigação preservada');await page.getByRole('button',{name:'Salvar título',exact:true}).click();
  await page.getByRole('button',{name:'Importar JSON',exact:true}).click();await page.getByLabel('Arquivo JSON',{exact:true}).setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":999}')});await page.getByRole('status').filter({hasText:'Estrutura inválida'}).waitFor();assert.equal(await page.locator('.investigation-row').count(),1);
  await page.getByLabel('Arquivo JSON',{exact:true}).setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(json))});await page.waitForFunction(()=>document.querySelectorAll('.investigation-row').length===2);assert.equal(await page.locator('.investigation-row').count(),2);
  await page.getByRole('button',{name:'Explorar exemplo',exact:true}).first().click();assert.ok(await page.getByLabel('O que você quer descobrir?',{exact:true}).isDisabled());await page.getByRole('button',{name:'Criar minha cópia',exact:true}).first().click();assert.ok(await page.getByLabel('O que você quer descobrir?',{exact:true}).isEnabled());
  await page.getByRole('button',{name:'Minhas investigações',exact:true}).click();assert.equal(await page.locator('.investigation-row').count(),3);
  await page.locator('.investigation-row').first().getByRole('button',{name:'Excluir',exact:true}).click();await page.locator('#modal-content').getByRole('button',{name:'Excluir',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.investigation-row').length===2);assert.equal(await page.locator('.investigation-row').count(),2);
  await page.getByRole('button',{name:'Apagar todos os dados',exact:true}).click();await page.getByRole('button',{name:'Apagar tudo',exact:true}).click();await page.getByRole('heading',{name:'Que pergunta você quer investigar?',exact:true}).waitFor();assert.equal(await page.locator('.investigation-row').count(),0);
  await page.screenshot({path:`test-results/home-${viewport.width}.png`,fullPage:true});
  assert.deepEqual(errors,[]);await context.close();
 });
}finally{await browser?.close();await new Promise(r=>server.close(r));}
