import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,extname} from 'node:path';
import {createRequire} from 'node:module';
import {newInvestigation,envelope} from '../dist/assets/core.js';
const require=createRequire(import.meta.url);const {chromium}=require('playwright');
const root=resolve('dist'),mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp'};
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!path.startsWith(root+'/')&&path!==root){res.writeHead(403).end();return;}const target=path===root?root+'/index.html':path;res.setHeader('Content-Type',mime[extname(target)]||'application/octet-stream');res.end(await readFile(target));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`;await mkdir('test-results',{recursive:true});
async function saved(page){await page.waitForFunction(()=>document.querySelector('#save-state')?.textContent==='Salvo neste dispositivo');}
async function rows(page,n){await page.waitForFunction(n=>document.querySelectorAll('.investigation-row').length===n,n);}
let browser;
try{browser=await chromium.launch({headless:true});
for(const viewport of [{width:1360,height:900},{width:390,height:844}])await test(`claim to evidence to decision, safe import and deletion at ${viewport.width}px`,async()=>{
 const context=await browser.newContext({viewport,acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(url);await page.getByRole('heading',{name:'O que você quer colocar à prova?'}).waitFor();await page.screenshot({path:`test-results/home-${viewport.width}.png`,fullPage:true});
 await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').textContent(),'Ir para o conteúdo');await page.keyboard.press('Enter');assert.equal(await page.locator(':focus').getAttribute('id'),'main');
 await page.getByLabel('Sua afirmação ou pequeno texto',{exact:true}).fill('Todo site com HTTPS é confiável.');await saved(page);await page.getByRole('button',{name:'Investigar',exact:true}).click();await page.getByRole('heading',{name:'O que encontramos',exact:true}).waitFor();
 const source=page.getByRole('link',{name:'Abrir fonte original ↗'}).first();assert.match(await source.getAttribute('href'),/consumer.ftc.gov/);assert.equal(await source.getAttribute('rel'),'noopener noreferrer');await source.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');assert.ok(await source.evaluate(n=>getComputedStyle(n).outlineStyle!=='none'));const popup=page.waitForEvent('popup');await context.route('https://consumer.ftc.gov/**',r=>r.fulfill({contentType:'text/html',body:'<p>Fonte externa simulada apenas no teste de abertura.</p>'}));await source.click();const external=await popup;assert.match(external.url(),/consumer.ftc.gov/);await external.close();
 await page.locator('.evidence').first().getByText('Contexto, datas e limitações',{exact:true}).click();await page.getByRole('button',{name:'Não consegui abrir esta fonte',exact:true}).first().click();await page.getByRole('button',{name:'Fonte voltou a abrir',exact:true}).waitFor();
 await page.getByLabel('Minha decisão',{exact:true}).selectOption('revise');await page.getByLabel('Minha justificativa ou frase revisada (opcional)',{exact:true}).fill('HTTPS protege a conexão. <img src=x onerror="window.pwned=true">');await saved(page);assert.equal(await page.locator('#main img').count(),0);assert.equal(await page.evaluate(()=>window.pwned),undefined);
 await page.screenshot({path:`test-results/result-${viewport.width}.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.getByRole('button',{name:'Exportar registro',exact:true}).click();assert.equal(await page.locator('#modal-content img').count(),0);assert.ok((await page.locator('#modal-content').innerText()).includes('<img src=x'));
 const jsonPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar JSON',exact:true}).click();const jsonDownload=await jsonPromise,json=JSON.parse(await readFile(await jsonDownload.path(),'utf8'));assert.equal(json.version,2);assert.equal(json.checks[0].decision,'revise');assert.equal(json.checks[0].unavailable.length,1);
 const mdPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar Markdown',exact:true}).click();assert.match(await readFile(await(await mdPromise).path(),'utf8'),/&lt;img/);
 await page.evaluate(()=>window.print=()=>{});await page.getByRole('button',{name:'Imprimir / salvar PDF',exact:true}).click();await page.emulateMedia({media:'print'});assert.equal(await page.locator('#print-report').evaluate(n=>getComputedStyle(n).display),'block');assert.equal(await page.locator('#main').evaluate(n=>getComputedStyle(n).display),'none');await page.pdf({path:`test-results/report-${viewport.width}.pdf`,format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});await page.getByRole('button',{name:'Fechar janela',exact:true}).click();
 await page.reload();await page.getByRole('button',{name:'Minhas investigações',exact:true}).click();await rows(page,1);await page.getByRole('button',{name:'Continuar',exact:true}).click();assert.equal(await page.getByLabel('Minha decisão',{exact:true}).inputValue(),'revise');assert.match(await page.getByLabel('Minha justificativa ou frase revisada (opcional)',{exact:true}).inputValue(),/HTTPS/);
 await page.getByRole('button',{name:'Minhas investigações',exact:true}).click();await page.getByRole('button',{name:'Renomear',exact:true}).click();await page.getByLabel('Título da investigação',{exact:true}).fill('Minha análise');await page.getByRole('button',{name:'Salvar título',exact:true}).click();await page.getByRole('heading',{name:'Minha análise',exact:true}).waitFor();
 await page.getByText('Importar um backup',{exact:true}).click();await page.getByLabel('Arquivo JSON',{exact:true}).setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});await page.getByRole('status').filter({hasText:'Estrutura inválida'}).waitFor();await rows(page,1);
 await page.getByLabel('Arquivo JSON',{exact:true}).setInputFiles({name:'good.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(json))});await rows(page,2);await page.locator('.investigation-row').last().getByRole('button',{name:'Continuar',exact:true}).click();await page.getByText('Registro importado: o aplicativo não autentica suas fontes ou resumos. Confira o original.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Minhas investigações',exact:true}).click();await page.locator('.investigation-row').first().getByRole('button',{name:'Excluir',exact:true}).click();await page.getByRole('button',{name:'Excluir definitivamente',exact:true}).click();await rows(page,1);
 await page.getByRole('button',{name:'Apagar todos os dados',exact:true}).click();await page.getByRole('button',{name:'Apagar tudo',exact:true}).click();await page.getByRole('heading',{name:'O que você quer colocar à prova?'}).waitFor();await page.getByRole('button',{name:'Minhas investigações',exact:true}).click();await rows(page,0);
 await page.getByRole('button',{name:'Voltar ao início',exact:true}).click();await page.evaluate(()=>document.documentElement.style.fontSize='32px');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.evaluate(()=>document.documentElement.style.fontSize='');assert.deepEqual(errors,[]);
 }catch(e){await page.screenshot({path:`test-results/failure-${viewport.width}.png`,fullPage:true});console.log(await page.locator('body').innerText());throw e;}finally{await context.close();}
});
await test('ambiguity, multiple claims, empty evidence and recoverable search failure',async()=>{const context=await browser.newContext(),page=await context.newPage();try{
 await page.goto(url);await page.getByLabel('Sua afirmação ou pequeno texto',{exact:true}).fill('A tecnologia faz mal');await page.getByRole('button',{name:'Investigar',exact:true}).click();await page.getByLabel('Como você entende esta frase?',{exact:true}).waitFor();assert.equal(await page.getByLabel('Como você entende esta frase?',{exact:true}).inputValue(),'context');await page.getByLabel('Afirmação que vamos investigar',{exact:true}).fill('O melhor navegador para mim é o Chrome em modo anônimo');await page.getByLabel('Como você entende esta frase?',{exact:true}).selectOption('opinion');await page.getByRole('button',{name:'Buscar evidências',exact:true}).click();await page.getByRole('heading',{name:'O que encontramos',exact:true}).waitFor();await page.getByText('Você está examinando um juízo de valor.',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Nova investigação',exact:true}).click();await page.getByLabel('Sua afirmação ou pequeno texto',{exact:true}).fill('O preço do arroz aumentou ontem');await page.getByRole('button',{name:'Investigar',exact:true}).click();await page.getByRole('heading',{name:'O que encontramos',exact:true}).waitFor();assert.equal(await page.locator('.evidence').count(),0);assert.match(await page.locator('main').innerText(),/Isso não mostra que ela é falsa ou verdadeira/);await page.getByLabel('Minha decisão',{exact:true}).selectOption('suspend');
 await page.getByRole('button',{name:'Nova investigação',exact:true}).click();await page.getByLabel('Sua afirmação ou pequeno texto',{exact:true}).fill('Todo gráfico começa em zero. A Lua não gira. HTTPS garante segurança.');await page.getByRole('button',{name:'Investigar',exact:true}).click();await page.getByLabel('Afirmação que vamos investigar',{exact:true}).waitFor();assert.equal(await page.locator('.choices button').count(),3);await page.locator('.choices button').nth(1).click();assert.equal(await page.getByLabel('Afirmação que vamos investigar',{exact:true}).inputValue(),'A Lua não gira.');
 }finally{await context.close();}
 const failContext=await browser.newContext(),p=await failContext.newPage();try{let failed=false;await p.route('**/search.js*',route=>{if(!failed){failed=true;return route.fulfill({status:503,body:'unavailable'});}return route.continue();});await p.goto(url);await p.getByLabel('Sua afirmação ou pequeno texto',{exact:true}).fill('HTTPS garante honestidade');await p.getByRole('button',{name:'Investigar',exact:true}).click();await p.getByRole('heading',{name:'O acervo não pôde ser aberto.',exact:true}).waitFor();assert.equal(await p.locator('.evidence').count(),0);await p.getByRole('button',{name:'Tentar novamente',exact:true}).click();await p.getByRole('heading',{name:'O que encontramos',exact:true}).waitFor();}finally{await failContext.close();}});
await test('database v1 upgrades without changing a legacy record and accepts v1 import',async()=>{const context=await browser.newContext(),page=await context.newPage();try{const legacy=newInvestigation('Registro anterior');legacy.question='Pergunta original';legacy.initial='Entendimento anterior';legacy.conclusion='Conclusão preservada';await page.goto(url);await page.evaluate(async data=>{await new Promise((resolve,reject)=>{const req=indexedDB.open('contraprova',1);req.onupgradeneeded=()=>{req.result.createObjectStore('investigations',{keyPath:'id'});req.result.createObjectStore('preferences',{keyPath:'key'});};req.onsuccess=()=>{const db=req.result,tx=db.transaction('investigations','readwrite');tx.objectStore('investigations').put(data);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};req.onerror=()=>reject(req.error);});},legacy);
 await page.getByRole('button',{name:'Minhas investigações',exact:true}).click();await page.getByRole('heading',{name:'Registros da versão anterior',exact:true}).waitFor();const actual=await page.evaluate(async()=>{const req=indexedDB.open('contraprova',2);return await new Promise(resolve=>{req.onsuccess=()=>{const db=req.result,q=db.transaction('investigations','readonly').objectStore('investigations').getAll();q.onsuccess=()=>{db.close();resolve(q.result[0]);};};});});assert.deepEqual(actual,legacy);await page.getByRole('button',{name:'Ver relatório',exact:true}).click();assert.match(await page.locator('#modal-content').innerText(),/Conclusão preservada/);await page.getByRole('button',{name:'Fechar janela',exact:true}).click();await page.getByText('Importar um backup',{exact:true}).click();await page.getByLabel('Arquivo JSON',{exact:true}).setInputFiles({name:'v1.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(envelope([legacy])))});await rows(page,2);
 }finally{await context.close();}});
await test('draft survives full browser process close and restart',async()=>{const profile=await mkdtemp(resolve(tmpdir(),'contraprova-profile-'));let persistent;try{persistent=await chromium.launchPersistentContext(profile,{headless:true});let page=await persistent.newPage();await page.goto(url);await page.getByLabel('Sua afirmação ou pequeno texto',{exact:true}).fill('Rascunho depois de reiniciar');await saved(page);await persistent.close();persistent=await chromium.launchPersistentContext(profile,{headless:true});page=await persistent.newPage();await page.goto(url);await page.getByRole('button',{name:'Minhas investigações',exact:true}).click();await page.getByRole('button',{name:'Continuar',exact:true}).click();assert.equal(await page.getByLabel('Sua afirmação ou pequeno texto',{exact:true}).inputValue(),'Rascunho depois de reiniciar');}finally{await persistent?.close();await rm(profile,{recursive:true,force:true});}});
}finally{await browser?.close();await new Promise(r=>server.close(r));}
