import {test} from 'node:test';
import assert from 'node:assert/strict';
import {search,candidates,suggestKind} from '../dist/assets/search.js';
import {sources} from '../dist/assets/corpus.js';
import {newCheck,bundle,parseBundle,copyBundle,markdown} from '../dist/assets/checks.js';
import {newInvestigation,envelope} from '../dist/assets/core.js';
test('retrieval provides real provenance, bounded coverage and no reversed verdict for negation',()=>{for(const q of ['HTTPS garante honestidade','HTTPS não garante honestidade']){const r=search(q);assert.equal(r.topic,'https');assert.match(r.evidence[0].source.url,/consumer.ftc.gov/);assert.match(r.summary,/não verifica/);}assert.equal(search('O preço do arroz aumentou nesta semana').evidence.length,0);assert.equal(search('Todo gráfico precisa começar em zero').evidence.length,2);assert.equal(sources.length,7);});
test('interpretation is editable suggestion, not forced factual verdict',()=>{assert.equal(candidates('Uma frase. Outra frase. Terceira. Quarta.').length,3);assert.equal(suggestKind('A tecnologia faz mal'),'context');assert.equal(suggestKind('O melhor site'),'opinion');assert.equal(suggestKind('A Lua será explorada'),'prediction');});
test('new and legacy imports preserve records, copy identifiers and bound inputs',()=>{const c=newCheck('<img src=x onerror=alert(1)>');c.claim='HTTPS';c.result=search(c.claim);c.reason='<script>alert(1)</script>';const old=newInvestigation();old.initial='Antes';old.conclusion='Depois';const b=parseBundle(JSON.stringify(bundle([c],[old])));assert.deepEqual(b.checks[0],c);assert.equal(b.investigations[0].initial,'Antes');assert.equal(copyBundle(b).checks[0].origin,'imported');assert.notEqual(copyBundle(b).checks[0].id,c.id);assert.equal(parseBundle(JSON.stringify(envelope([old]))).investigations[0].conclusion,'Depois');assert.match(markdown(c),/&lt;script&gt;/);for(const change of [x=>x.version=99,x=>x.checks[0].input='a'.repeat(6001),x=>x.checks[0].result.evidence[0].source.url='javascript:alert(1)',x=>x.checks[0].result.evidence[0].source.url='https://user:pass@example.org',x=>x.checks[0].result.evidence[0].source.extra=true,x=>x.checks.push(x.checks[0])]){const bad=bundle([c],[old]);change(bad);assert.throws(()=>parseBundle(JSON.stringify(bad)));}assert.throws(()=>parseBundle('a'.repeat(2*1024*1024+1)));});
